### ISSUE TITLE
Rename gem to jekyll_picture_tag

### ISSUE THREAD

**Issue by rbuchberger** [rbuchberger/jekyll-picture-tag#120]
There are 2 reasons for this change:
* Best practice says we should use underscores and not dashes.
* We've lost push access to `jekyll-picture-tag` on rubygems.

The second is by far the bigger issue. During the time this plugin was stale, its original authors mostly moved on with their lives. I've tried to contact the owner of `jekyll-picture-tag` on rubygems via every channel I can find, without success. 

From version 1.0 until now, it has been necessary to install jpt directly from this git repo, requiring an annoyingly verbose gemfile specification. This change fixes that, by renaming the plugin from `jekyll-picture-tag` to `jekyll_picture_tag`. 

The problem here is that if I just rename everything and push it, everyone who has followed the installation instructions for the past several months will see their site break. (Their gemfile will reference the old name at this github repo, which it won't find here!) 

To handle this, we create a duplicate gemspec under the old name which will load its corresponding `rb` file under `lib`. This file will print a warning message and then require the new one.

**Comment by robwierzbowski** [comment]
The owner is me! This is just never on my priority list. I've also lost my rubygems creds, and moved emails, so it's not as simple as just taking 10 mins out of the day.

I think this is a great direction.

**Comment by robwierzbowski** [comment]
Would you also like me to transfer this repo into your GH? Lemme see if I can do that now...

**Comment by robwierzbowski** [comment]
Looks like you have to delete your clone first.

**Comment by rbuchberger** [comment]
Done! I think that would definitely make things simpler, if you don't mind.

**Comment by robwierzbowski** [comment]
Done!

Thank you, and enjoy.

Rob Wierzbowski
http://robwierzbowski.com

**Comment by rbuchberger** [comment]
Thank you much! I'll take good care of it.

I opened a ticket on rubygems asking for access; if that works out maybe we can avoid the rename altogether. Worst they can say is no
