### ISSUE TITLE
Attributes applied to indivdual tags are applied to other tags with the same preset

### ISSUE THREAD

**Issue by rbuchberger** [rbuchberger/jekyll-picture-tag#123]
Example: on one page

```
{% picture my_preset image.jpg --picture class="my-class" %}
```

Somewhere else:
```
{% picture my_preset image.jpg %}
```

The second image will be rendered with `class="my-class"`. I haven't yet done any troubleshooting to determine if this is all the time, or only under certain circumstances.

**Comment by YJPL** [comment]
Got the same unexpected results with `--link`. If for instance one picture is set to:

```{% picture image.jpg --link example.com %}```

other pictures will also link to `example.com`.
