### ISSUE TITLE
Generated picture size inaccurate

### ISSUE THREAD

**Issue by timakro** [rbuchberger/jekyll-picture-tag#125]
The generated image for width 720 actually has a width of 721 pixels. When the browser renders it at 720 pixels it looks blurry (it contains text).

Can you explain why this happens?

Is it a bad idea to provide image widths exactly as they will be rendered in the browser? Should I better provide images a little bit bigger (e.g. 800 instead of 720) so they never look blurry when rendered in smaller resolutions?

**Comment by rbuchberger** [comment]
Huh... You're right! I don't know why imagemagick would add a pixel. Will have to research this more. Nice catch.

As far as providing images exactly as they will be rendered, it's fine but make sure that you're aware of [device pixel ratios](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio). Basically different devices might have multiple physical pixels per CSS pixel, depending on the screen. They range all the way from 1 to ~3.5.

**Comment by timakro** [comment]
Probably ImageMagick calculates the image height differently than the [implementation in generated_image.rb](https://github.com/robwierzbowski/jekyll-picture-tag/blob/0bff9bf84d53239824dbe5cd373e26fcae690fbb/lib/jekyll-picture-tag/generated_image.rb#L35-L38). The solution would be to just pass the width to ImageMagick and let it work out the height by itself. [This solution](https://stackoverflow.com/a/7201084/3235192) works with the `convert` tool, not sure if the Ruby binding supports it though.

PS: Do you know of any statistics for "true" mobile screen resolutions? All statistics I could find e.g. [statcounter.com](http://gs.statcounter.com/screen-resolution-stats/mobile/worldwide) don't seem to be considering device pixel ratios.

**Comment by timakro** [comment]
Yep, that works. I opened a pull request #126.
